name: Testes de Unidade

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  checkout_codigo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2
      
  checkout_dotnet:
    runs-on: ubuntu-latest
    
    needs: checkout_codigo
    steps:
    - name: Setup do .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
  restore_packages:
    runs-on: ubuntu-latest
  
    needs: checkout_dotnet
    steps:
    - name: Restaurar pacotes
      run: dotnet restore CursoXunit.DominioTest/CursoXunit.DominioTest.csproj
  build:
    runs-on: ubuntu-latest
    
    needs: restore_packages
    steps:
    - name: Compilar
      run: dotnet build --configuration Release
  tests:
    runs-on: ubuntu-latest
    
    needs: build
    steps:
    - name: Executar testes de unidade
      run: dotnet test CursoXunit.DominioTest/Cursos/CursoTests.cs --filter FullyQualifiedName~NaoDeveTerUmNameVazio
